"""Tests for the JAMEL estimate generator (both pricing modes).

Golden fixtures: ``golden/{range,fixed}-input.json`` + ``-golden.xlsx``.
The golden .xlsx files were generated by this code and manually reviewed
against the reference estimates (``offers/estimates/sprint-est.xlsx`` and
``ina-management-est.xlsx``) before committing. Regenerate after intended
render changes:

    ../.venv/bin/python regenerate_golden.py
"""
from __future__ import annotations

import json
import zipfile
from decimal import Decimal
from io import BytesIO
from pathlib import Path

import openpyxl
import pytest

from generate_wycena_xlsx import (
    ROLE_RATES,
    TEMPLATE_PATH,
    assemble_line_items,
    generate_from_payload,
    sum_totals,
)

GOLDEN_DIR = Path(__file__).resolve().parent / "golden"


def load_payload(name: str) -> dict:
    return json.loads((GOLDEN_DIR / f"{name}-input.json").read_text(encoding="utf-8"))


def render(payload: dict) -> openpyxl.Workbook:
    return openpyxl.load_workbook(BytesIO(generate_from_payload(payload)))


# ===========================================================================
# Data layer
# ===========================================================================
def _meta() -> dict:
    return {"title": "wdrożenia serwisu", "client_name": "X",
            "author": {"first_name": "A", "last_name": "B"}}


def test_numbering_follows_explicit_stage_order():
    payload = {
        "meta": _meta(),
        "pricing_mode": "range",
        "stages": ["Analiza i projektowanie", "Programowanie"],
        "line_items": [
            {"stage": "Programowanie", "title": "b", "role": "Programista", "hours_min": 1, "hours_max": 2},
            {"stage": "Analiza i projektowanie", "title": "a", "role": "Web Designer", "hours_min": 1, "hours_max": 2},
            {"stage": "Programowanie", "title": "c", "role": "Programista", "hours_min": 1, "hours_max": 2},
            {"stage": "Ekstra", "title": "d", "role": "Tester", "hours_min": 1, "hours_max": 2},
        ],
    }
    items = assemble_line_items(payload)
    numbered = {li.title: li.display_number for li in items}
    # Explicit stages come first regardless of item order; unknown stages append.
    assert numbered == {"a": "1.1", "b": "2.1", "c": "2.2", "d": "3.1"}
    assert all(isinstance(li.display_number, str) for li in items)


def test_empty_stage_renders_banner_only():
    payload = {
        "meta": _meta(),
        "pricing_mode": "range",
        "stages": ["Programowanie", "Zakończenie prac"],
        "line_items": [
            {"stage": "Programowanie", "title": "a", "role": "Programista", "hours_min": 1, "hours_max": 2},
        ],
    }
    items = assemble_line_items(payload)
    banner = [li for li in items if li.item_order == 0]
    assert len(banner) == 1 and banner[0].stage == "Zakończenie prac"

    ws = render(payload)["Wycena"]
    banners = [c.value for row in ws.iter_rows(min_col=2, max_col=2) for c in row]
    assert "Zakończenie prac" in banners


def test_rate_resolution_chain():
    payload = {
        "meta": {**_meta(), "default_hourly_rate": 100},
        "pricing_mode": "fixed",
        "role_rates": {"Web Designer": 300},
        "line_items": [
            {"stage": "s", "title": "override", "role": "Web Designer", "hours": 1, "hourly_rate": 400},
            {"stage": "s", "title": "payload", "role": "Web Designer", "hours": 1},
            {"stage": "s", "title": "builtin", "role": "Tester", "hours": 1},
            {"stage": "s", "title": "fallback", "role": "Nieznana Rola", "hours": 1},
        ],
    }
    rates = {li.title: li.hourly_rate for li in assemble_line_items(payload)}
    assert rates == {"override": Decimal("400"), "payload": Decimal("300"),
                     "builtin": ROLE_RATES["Tester"], "fallback": Decimal("100")}


def test_kinds_and_totals():
    payload = {
        "meta": _meta(),
        "pricing_mode": "range",
        "line_items": [
            {"stage": "s", "title": "hourly", "role": "Tester", "hours_min": 10, "hours_max": 20},
            {"stage": "s", "title": "ryczałt", "role": "Copywriter", "kind": "fixed",
             "amount_min": 4500, "amount_max": 7000},
            {"stage": "s", "title": "rabat", "role": "Project Manager", "kind": "fixed", "amount": -1000},
            {"stage": "s", "title": "w cenie", "role": "Project Manager", "kind": "included", "hours": 2},
        ],
    }
    items = assemble_line_items(payload)
    by_title = {li.title: li for li in items}
    assert by_title["hourly"].total_min == Decimal("1800")
    assert by_title["hourly"].total_max == Decimal("3600")
    assert by_title["ryczałt"].total_min == Decimal("4500")
    assert by_title["rabat"].total_min == by_title["rabat"].total_max == Decimal("-1000")
    assert by_title["w cenie"].total_min == Decimal("0")
    assert sum_totals(items) == (Decimal("5300"), Decimal("9600"))


def test_invalid_items_raise():
    base = {"meta": _meta(), "pricing_mode": "fixed"}
    with pytest.raises(ValueError, match="kind"):
        assemble_line_items({**base, "line_items": [
            {"stage": "s", "title": "x", "role": "Tester", "kind": "nope"}]})
    with pytest.raises(ValueError, match="hours"):
        assemble_line_items({**base, "line_items": [
            {"stage": "s", "title": "x", "role": "Tester"}]})
    with pytest.raises(ValueError, match="amount"):
        assemble_line_items({**base, "line_items": [
            {"stage": "s", "title": "x", "role": "Tester", "kind": "fixed"}]})
    with pytest.raises(ValueError, match="pricing_mode"):
        generate_from_payload({"meta": _meta(), "line_items": []})


# ===========================================================================
# Structural render checks
# ===========================================================================
RANGE_HEADERS = ["Etap", "Opis", "Zadanie Wykonawcy", "Rola", "RH (min)", "RH (max)",
                 "Stawka", "Kwota całkowita netto (min)", "Kwota całkowita netto (max)"]
FIXED_HEADERS = ["Etap", "Opis", "Zadanie Wykonawcy", "Rola", "RH", "Stawka",
                 "Kwota całkowita netto"]


def _cells(ws):
    return [c for row in ws.iter_rows() for c in row if c.value is not None]


def test_range_structure():
    wb = render(load_payload("range"))
    assert wb.sheetnames == ["Wycena", "Elementy dodatkowe"]
    ws = wb["Wycena"]

    assert [ws.cell(row=5, column=c).value for c in range(2, 11)] == RANGE_HEADERS
    assert ws["C1"].value == "Wycena wdrożenia serwisu\ndla Sprint"
    assert ws.sheet_view.showGridLines is False

    payload = load_payload("range")
    hourly = [i for i in payload["line_items"] if i.get("kind", "hourly") == "hourly"]
    formulas_i = [c.value for c in _cells(ws) if isinstance(c.value, str) and c.value.startswith("=F") and "*H" in c.value]
    formulas_j = [c.value for c in _cells(ws) if isinstance(c.value, str) and c.value.startswith("=G") and "*H" in c.value]
    assert len(formulas_i) == len(formulas_j) == len(hourly)

    # Ryczałt row: '-' markers + literal amounts.
    ryczalt_row = next(r for r in range(6, ws.max_row) if ws.cell(row=r, column=3).value == "Copywriting")
    assert [ws.cell(row=ryczalt_row, column=c).value for c in (6, 7, 8, 9, 10)] == ["-", "-", "-", 4500, 7000]

    # Included row: hours visible, zero rate and amounts.
    incl_row = next(r for r in range(6, ws.max_row) if ws.cell(row=r, column=3).value == "Szkolenie")
    assert [ws.cell(row=incl_row, column=c).value for c in (6, 7, 8, 9, 10)] == [2, 2, 0, 0, 0]

    # SUMA: labels + contiguous =SUM over exactly the item rows.
    sum_row = next(r for r in range(6, ws.max_row + 1) if ws.cell(row=r, column=9).value == "SUMA (min)")
    assert ws.cell(row=sum_row, column=10).value == "SUMA (max)"
    item_rows = [r for r in range(6, ws.max_row) if isinstance(ws.cell(row=r, column=2).value, str)
                 and "." in str(ws.cell(row=r, column=2).value)]
    assert ws.cell(row=sum_row + 1, column=9).value == f"=SUM(I{item_rows[0]}:I{item_rows[-1]})"
    assert ws.cell(row=sum_row + 1, column=10).value == f"=SUM(J{item_rows[0]}:J{item_rows[-1]})"

    # Hours/rates are typed numbers, not strings; item numbers are text.
    first_item = item_rows[0]
    assert isinstance(ws.cell(row=first_item, column=6).value, (int, float))
    assert isinstance(ws.cell(row=first_item, column=8).value, (int, float))
    assert ws.cell(row=first_item, column=2).value == "1.1"

    # No unsubstituted placeholders anywhere.
    for sheet in wb.sheetnames:
        assert not any("{{" in str(c.value) for c in _cells(wb[sheet]))

    # Coral banner + coral SUMA values (spot style checks).
    banner_row = next(r for r in range(6, ws.max_row) if ws.cell(row=r, column=2).value == "Programowanie")
    assert ws.cell(row=banner_row, column=2).font.color.rgb == "FFFF818D"
    assert ws.cell(row=sum_row + 1, column=9).fill.fgColor.rgb == "FFFF818D"


def test_fixed_structure():
    payload = load_payload("fixed")
    wb = render(payload)
    assert wb.sheetnames == ["Wycena"]  # no additional_items -> single sheet
    ws = wb["Wycena"]

    assert [ws.cell(row=5, column=c).value for c in range(2, 9)] == FIXED_HEADERS

    hourly = [i for i in payload["line_items"] if i.get("kind", "hourly") == "hourly"]
    formulas = [c.value for c in _cells(ws) if isinstance(c.value, str) and c.value.startswith("=F") and "*G" in c.value]
    assert len(formulas) == len(hourly)

    rabat_row = next(r for r in range(6, ws.max_row) if ws.cell(row=r, column=3).value == "Rabat")
    assert ws.cell(row=rabat_row, column=8).value == -1000

    incl_row = next(r for r in range(6, ws.max_row) if ws.cell(row=r, column=3).value == "Szkolenie")
    assert ws.cell(row=incl_row, column=6).value == "W cenie"
    assert ws.cell(row=incl_row, column=8).value is None

    sum_row = next(r for r in range(6, ws.max_row + 1) if ws.cell(row=r, column=7).value == "SUMA")
    item_rows = [r for r in range(6, ws.max_row) if isinstance(ws.cell(row=r, column=2).value, str)
                 and "." in str(ws.cell(row=r, column=2).value)]
    assert ws.cell(row=sum_row, column=8).value == f"=SUM(H{item_rows[0]}:H{item_rows[-1]})"
    assert ws.cell(row=sum_row, column=8).fill.fgColor.rgb == "FFFF818D"


def test_band_verification_matches_formula_semantics():
    """sum_totals must equal what the sheet formulas would evaluate to."""
    payload = load_payload("range")
    total_min, total_max = sum_totals(assemble_line_items(payload))
    expected_min = expected_max = Decimal("0")
    for item in payload["line_items"]:
        kind = item.get("kind", "hourly")
        if kind == "hourly":
            rate = ROLE_RATES[item["role"]]
            expected_min += Decimal(str(item["hours_min"])) * rate
            expected_max += Decimal(str(item["hours_max"])) * rate
        elif kind == "fixed":
            expected_min += Decimal(str(item.get("amount_min", item.get("amount"))))
            expected_max += Decimal(str(item.get("amount_max", item.get("amount"))))
    assert (total_min, total_max) == (expected_min, expected_max)


# ===========================================================================
# Golden render comparison
# ===========================================================================
@pytest.mark.parametrize("name", ["range", "fixed"])
def test_matches_golden_render(name: str):
    golden_path = GOLDEN_DIR / f"{name}-golden.xlsx"
    assert golden_path.exists(), "run regenerate_golden.py and review the output first"

    generated = openpyxl.load_workbook(BytesIO(generate_from_payload(load_payload(name))))
    golden = openpyxl.load_workbook(golden_path)

    assert generated.sheetnames == golden.sheetnames
    for sheet in golden.sheetnames:
        gws, ows = generated[sheet], golden[sheet]
        assert gws.max_row == ows.max_row and gws.max_column == ows.max_column
        assert sorted(str(r) for r in gws.merged_cells.ranges) == \
               sorted(str(r) for r in ows.merged_cells.ranges)
        for grow, orow in zip(gws.iter_rows(), ows.iter_rows()):
            for gcell, ocell in zip(grow, orow):
                coord = f"{sheet}!{gcell.coordinate}"
                assert gcell.value == ocell.value, coord
                assert gcell.number_format == ocell.number_format, coord
                gfill = gcell.fill.fgColor.rgb if gcell.fill.fill_type else None
                ofill = ocell.fill.fgColor.rgb if ocell.fill.fill_type else None
                assert gfill == ofill, coord


# ===========================================================================
# Template invariants
# ===========================================================================
def test_template_has_all_blocks_and_logo():
    wb = openpyxl.load_workbook(TEMPLATE_PATH)
    for mode in ("range", "fixed"):
        for block in ("estimate-header", "etap-header", "line-item-first", "line-item-middle",
                      "line-item-last", "line-item-single", "sum", "last-row"):
            assert f"{block}-{mode}" in wb.sheetnames, f"{block}-{mode} missing"
    with zipfile.ZipFile(TEMPLATE_PATH) as zf:
        assert len(zf.read("xl/media/image1.png")) > 0
